version: '3.0'

services:
  grafana:
    container_name: 'computest-cloudwatchalarm-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/computest-cloudwatchalarm-datasource
      - ./provisioning:/etc/grafana/provisioning
