name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Build and test frontend
        run: npm run build

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.1"

      - name: Test backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: coverage

      - name: Build backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: buildAll
